using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using Newtonsoft.Json;

namespace tiktok_Omni.Services
{
    /// <summary>
    /// Persistent data model for one row in any platform's schedule grid.
    /// </summary>
    public sealed class ScheduleEntry
    {
        public string VideoFilePath { get; set; } = string.Empty;
        public string VideoLabel    { get; set; } = string.Empty;

        public DateTime? ScheduledAt { get; set; }

        /// <summary>
        /// Read/write text binding for the "Giờ đăng" DataGridView column.
        /// Getter: formats the stored DateTime; setter: parses back or clears.
        /// </summary>
        public string ScheduledAtText
        {
            get => ScheduledAt.HasValue
                ? ScheduledAt.Value.ToString("dd/MM/yyyy HH:mm")
                : "Đăng ngay";
            set
            {
                var v = (value ?? string.Empty).Trim();
                if (v.Length == 0 || string.Equals(v, "Đăng ngay", StringComparison.OrdinalIgnoreCase))
                    ScheduledAt = null;
                else if (DateTime.TryParseExact(v, "dd/MM/yyyy HH:mm",
                         CultureInfo.InvariantCulture, DateTimeStyles.None, out var exact))
                    ScheduledAt = exact;
                else if (DateTime.TryParse(v, CultureInfo.CurrentCulture, DateTimeStyles.None, out var dt))
                    ScheduledAt = dt;
            }
        }

        // ── Caption storage ───────────────────────────────────────────────────
        // AllCaptions stores up to 5 style variants generated by Gemini.
        // Caption (kept for backward compat + posting logic) mirrors the chosen variant.
        public Dictionary<string, string> AllCaptions { get; set; } = new Dictionary<string, string>();

        /// <summary>Which of the 5 style keys is currently chosen ("fomo", "ke_chuyen", etc.).</summary>
        public string SelectedCaptionKey { get; set; } = string.Empty;

        /// <summary>
        /// The resolved, ready-to-post caption body.
        /// Setter lets legacy code and posting pipeline write directly.
        /// Getter prefers AllCaptions[SelectedCaptionKey], falls back to stored _caption.
        /// </summary>
        public string Caption
        {
            get
            {
                if (!string.IsNullOrWhiteSpace(SelectedCaptionKey) &&
                    AllCaptions != null &&
                    AllCaptions.TryGetValue(SelectedCaptionKey, out var v) &&
                    !string.IsNullOrWhiteSpace(v))
                    return v;
                return _caption;
            }
            set
            {
                _caption = value ?? string.Empty;
                // If the user typed directly (value differs from the selected style),
                // clear the style key so the manually typed text is used for posting.
                if (!string.IsNullOrWhiteSpace(SelectedCaptionKey) &&
                    AllCaptions != null &&
                    AllCaptions.TryGetValue(SelectedCaptionKey, out var styled) &&
                    !string.Equals(styled, _caption, StringComparison.Ordinal))
                {
                    SelectedCaptionKey = string.Empty;
                }
            }
        }

        [JsonIgnore]
        private string _caption = string.Empty;

        // ── YouTube-specific fields ───────────────────────────────────────────
        // AllCaptions is also used for YouTube (value format: "TITLE|||DESCRIPTION+hashtags").
        public string YtTitle       { get; set; } = string.Empty;
        public string YtDescription { get; set; } = string.Empty;

        public string Link    { get; set; } = string.Empty;
        public string Hashtag { get; set; } = string.Empty;
        public string Status  { get; set; } = "Pending";
        public string Profile { get; set; } = string.Empty;

        [JsonIgnore]
        public string LastError { get; set; } = string.Empty;

        // ── Grid display labels ───────────────────────────────────────────────
        [JsonIgnore]
        public string CaptionStatusLabel
        {
            get
            {
                var count = AllCaptions?.Count ?? 0;
                if (count == 0 && string.IsNullOrWhiteSpace(Caption)) return "— chưa có —";
                if (count > 0 && !string.IsNullOrWhiteSpace(SelectedCaptionKey))
                {
                    var lbl = GetStyleLabel(SelectedCaptionKey);
                    return $"✓ {lbl}";
                }
                if (count > 0) return $"{count} phong cách";
                var preview = Caption;
                return preview.Length > 20 ? preview.Substring(0, 20) + "…" : preview;
            }
        }

        [JsonIgnore]
        public string HashtagPreview =>
            Hashtag?.Length > 24 ? Hashtag.Substring(0, 24) + "…" : (Hashtag ?? string.Empty);

        [JsonIgnore]
        public string YtTitlePreview =>
            YtTitle?.Length > 22 ? YtTitle.Substring(0, 22) + "…" : (YtTitle ?? string.Empty);

        [JsonIgnore]
        public string YtDescPreview =>
            YtDescription?.Length > 22 ? YtDescription.Substring(0, 22) + "…" : (YtDescription ?? string.Empty);

        public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;

        private static string GetStyleLabel(string key)
        {
            switch (key)
            {
                case "noi_dau":   return "Nỗi đau";
                case "boc_phot":  return "Bóc phốt";
                case "huong_dan": return "Hướng dẫn";
                case "fomo":      return "FOMO";
                case "ke_chuyen": return "Kể chuyện";
                default:          return key;
            }
        }
    }

    /// <summary>Root JSON model saved to disk.</summary>
    public sealed class ScheduleData
    {
        public List<ScheduleEntry> TikTok   { get; set; } = new List<ScheduleEntry>();
        public List<ScheduleEntry> Facebook { get; set; } = new List<ScheduleEntry>();
        public List<ScheduleEntry> YouTube  { get; set; } = new List<ScheduleEntry>();
    }

    /// <summary>
    /// Lưu 3 lưới lịch đăng (TikTok / Facebook / YouTube) — vị trí bền, không mất khi rebuild bin.
    /// </summary>
    public sealed class ScheduleManager
    {
        private readonly string _filePath;

        public ScheduleManager(string filePath = null)
        {
            _filePath = filePath ?? ResolveDefaultFilePath();
        }

        public static string DefaultFilePath => ResolveDefaultFilePath();

        private static string ResolveDefaultFilePath()
        {
            return AppDataPaths.PersistentFile("autopost_schedule.json");
        }

        private static string GetPersistentAppDataDirectory()
        {
            return AppDataPaths.EnsurePersistentRoot();
        }

        private static string ResolveReadableFilePath(out bool migrateFromLegacy)
        {
            migrateFromLegacy = false;
            return AppDataPaths.ResolveReadableJsonPath("autopost_schedule.json", out migrateFromLegacy);
        }

        public ScheduleData Load()
        {
            try
            {
                var path = ResolveReadableFilePath(out var migrateFromLegacy);
                if (!File.Exists(path))
                {
                    return new ScheduleData();
                }

                var json = File.ReadAllText(path, TextFileEncoding.Utf8);
                var data = JsonConvert.DeserializeObject<ScheduleData>(json) ?? new ScheduleData();
                if (migrateFromLegacy && HasAnyEntries(data))
                {
                    Save(data);
                }

                return data;
            }
            catch
            {
                return new ScheduleData();
            }
        }

        public void Save(ScheduleData data)
        {
            try
            {
                var target = _filePath ?? ResolveDefaultFilePath();
                Directory.CreateDirectory(Path.GetDirectoryName(target) ?? GetPersistentAppDataDirectory());
                var json = JsonConvert.SerializeObject(data ?? new ScheduleData(), Formatting.Indented);
                File.WriteAllText(target, json, TextFileEncoding.Utf8NoBom);
            }
            catch
            {
                // ignored
            }
        }

        private static bool HasAnyEntries(ScheduleData data)
        {
            if (data == null)
            {
                return false;
            }

            return (data.TikTok?.Count ?? 0) > 0
                || (data.Facebook?.Count ?? 0) > 0
                || (data.YouTube?.Count ?? 0) > 0;
        }
    }
}
